fix: 그룹 생성, 삭제 유저 인증 추가
99-12-node/sendinGo-BE pull request #156
Opened 2023-03-28 10:33 UTC by Ryeonjoo

2023-03-29 00:42 UTC, minenam commented on src/services/group.service.js
> +    }
여기 코드 중복 같아요. 어차피 createGroup할 때 userId를 넣는데 굳이 같은 userId를 확인하는 이유가 있을까요?

2023-03-29 00:42 UTC, minenam commented on src/services/group.service.js
> +    }
createGroup 과 같은 의견 입니다.

2023-03-29 00:44 UTC, minenam requested changes
해당 코드와 함께 models나 migration으로 테이블 변경 수정도 있어야 할 듯 한데요.
아직 PR 안 올라 온걸까요? 머지 및 배포한 경우 테이블에 없는 컬럼이라고 오류 날 수 도 있어서요.

2023-03-29 07:18 UTC, minenam commented on src/db/models/client.js
> +        allowNull: false,
여기 주석도 지워주셔도 돼요!

2023-03-29 07:19 UTC, minenam commented on src/services/group.service.js
> +    }
이부분 수정이 안 된 것 같습니다..! 혹시 지우지 않은 이유가 있을까요?

2023-03-29 07:20 UTC, minenam commented on src/services/client.service.js
> +    if (data.userId !== userId || data.companyId !== companyId) {
여긴 or 대신 and가 들어가야 하지 않을까 싶네요

2023-03-29 07:21 UTC, minenam commented on src/services/client.service.js
> +    if (data.userId !== userId || data.companyId !== companyId) {
여기도 or 대신 and 가 더 적합한 것 같아요!

2023-03-29 07:21 UTC, minenam commented on src/repositories/client.repository.js
> +      attributes: ['userId', 'companyId'],
where대신 attributes 에 들어간 이유가 있나요?

2023-03-29 09:06 UTC, Ryeonjoo commented on src/repositories/client.repository.js
> +      attributes: ['userId', 'companyId'],
만약 등록된 userId 1 의  clientId 11을 다른 userId 2가 clientId 11을 수정한다고 가정했을 때, where: { clientId, userId, companyId} where절에서 3개의 매개변수를 받으면 clientId와 userId, companyId가 일치하지 않아 속성을 읽을 수 없다는 에러가 떠요. 그래서 attributes을 사용했어요.

2023-03-30 06:22 UTC, Ryeonjoo commented on src/repositories/client.repository.js
> +      attributes: ['userId', 'companyId'],
수정했습니다.

2023-03-30 06:29 UTC, minenam commented on src/db/models/talkresultdetails.js
> +
주석 하면 되는 부분까지 처리 됐네요 확인 부탁드려요!

2023-03-30 06:51 UTC, minenam approved these changes

2023-03-30 06:51 UTC, merged